# Generated by Django 5.2.18 on 2026-10-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author_avatar",
            field=models.URLField(
                blank=True,
                default="https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="author_name",
            field=models.CharField(default="Alexander Vance", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="author_role",
            field=models.CharField(default="Lead Software Architect", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("technology", "Technology"),
                    ("design", "UI/UX Design"),
                    ("architecture", "Architecture"),
                    ("career", "Career & Insights"),
                ],
                default="technology",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.TextField(
                blank=True,
                help_text="Catchy teaser for article cards and hero spotlight",
                max_length=350,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload custom cover image",
                null=True,
                upload_to="posts/",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Optional direct cover image URL (Unsplash, CDN, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Feature this article in top Hero Spotlight on home page",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
