# Generated by Django 5.2.18 on 2026-10-07 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_author_avatar_post_author_name_post_author_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("date_sent", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date_sent"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_subscribed", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date_subscribed"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="audio_duration",
            field=models.CharField(
                blank=True,
                default="4 min audio",
                help_text="Audio narration duration badge",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="likes_count",
            field=models.PositiveIntegerField(default=42),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.CharField(
                default="Tech, Design, Cloud",
                help_text="Comma separated tags e.g. AI, Django, CSS",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("technology", "Technology & AI"),
                    ("design", "UI/UX Design"),
                    ("architecture", "System Architecture"),
                    ("career", "Career & Leadership"),
                ],
                default="technology",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("content", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
